name: Generate XML

on:
    push:
    schedule:
        - cron:  '0 12 * * *'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Install pipenv
          run: sudo pip install pipenv

        - name: Install dependencies using Pipenv
          run: pipenv install --deploy

        - name: Download dats, db and generate the XML
          id: generator
          run: pipenv run ./generator/main.py --download-dats --update-custom-dat ${{ secrets.SECRET_URL }} --download-db --generate-xml
          env:
              TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
              TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}

        - name: Store date into an environment variable
          env:
              ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
          run: echo "::set-env name=DATE::$(date '+%Y-%m-%d')"

        - name: Delete old drafts
          uses: hugo19941994/delete-draft-releases@v1.0.0
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Create Github release
          id: create_release
          uses: actions/create-release@v1.1.0
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              tag_name: ${{ github.ref }}
              release_name: DB ${{env.DATE}}
              body: ${{ steps.generator.outputs.GITHUB_RELEASE_MD }}
              draft: true
              prerelease: true

        - name: Upload zipped database into the release
          uses: actions/upload-release-asset@v1
          env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ./DB_${{env.DATE}}.zip
              asset_name: DB_${{env.DATE}}.zip
              asset_content_type: application/zip

        - name: Generate new PR with the updated custom MegaSD DAT file if needed
          uses: peter-evans/create-pull-request@v2.7.2
          with:
              commit-message: Update MegaSD Sega CD DAT
          env:
              ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"

